name: Test

# Controls when the action will run. Triggers the workflow on push on branch except main
# or pull request events but only for the main branch
on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: prepare before build
        run: |
           sudo apt-get install -qy make apt-transport-https ca-certificates software-properties-common gawk jq parallel curl language-pack-fr
           uname -a
           type -a docker-compose && docker-compose version
           docker version
           docker info

      - name: Build & test
        run: |
           set -e
           ci/build-and-test.sh
